### ISSUE TITLE
Python 3, Bazel errors

### ISSUE THREAD

**Issue by ksmskm** [yourbase/yourbase#98]
directory: `/Users/kyle/go/src/github.com/ksmskm/yourbase`

`bazel build @go_image_base//image`

```
ERROR: Skipping '@go_image_base//image': no such package '@go_image_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/__main__.py", line 30, in <module>
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/containerregistry/client/__init__.py", line 19, in <module>
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/containerregistry/client/docker_name_.py", line 21, in <module>
ModuleNotFoundError: No module named 'urlparse'
 (/usr/local/bin/python /private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par --directory /private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/go_image_base/image --name gcr.io/distroless/base@sha256:bef8d030c7f36dfb73a8c76137616faeea73ac5a8495d535f27c911d0db77af3)
WARNING: Target pattern parsing failed.
ERROR: no such package '@go_image_base//image': Pull command failed: Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/__main__.py", line 30, in <module>
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/containerregistry/client/__init__.py", line 19, in <module>
  File "/private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par/containerregistry/client/docker_name_.py", line 21, in <module>
ModuleNotFoundError: No module named 'urlparse'
 (/usr/local/bin/python /private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/puller/file/puller.par --directory /private/var/tmp/_bazel_kyle/97f1d2721e0c41a743f0f60caddbe034/external/go_image_base/image --name gcr.io/distroless/base@sha256:bef8d030c7f36dfb73a8c76137616faeea73ac5a8495d535f27c911d0db77af3)
INFO: Elapsed time: 3.575s
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by nictuku** [comment]
It looks like this could be https://github.com/bazelbuild/rules_docker/issues/293

**Comment by nictuku** [comment]
Let's keep this issue open until we can say with confidence that yourbase / rules_docker can be used reliably with python3.
